// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `central`, `conn_slot`, `device_slot`, `events_slot`, `forwarder_slot`, `lock`, `monitor_slot`, `rt`, `teardown_current`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// The session inbound stream: every notification payload, across connect
/// cycles, arrives here as a `Stream<Uint8List>`. Call ONCE at startup.
Stream<Uint8List> bleEvents() => RustLib.instance.api.crateApiBleBleEvents();

/// The session connection-state stream: `true` after a connect, `false` when the
/// connected device disconnects (drop or explicit). The app decides policy
/// (e.g. auto-reconnect on an unexpected drop). Call ONCE at startup.
Stream<bool> connectionEvents() =>
    RustLib.instance.api.crateApiBleConnectionEvents();

/// Scan for [timeout_ms] and return the visible BLE devices (named ones first).
Future<List<BleDevice>> scan({required BigInt timeoutMs}) =>
    RustLib.instance.api.crateApiBleScan(timeoutMs: timeoutMs);

/// Scan, connect to the device whose advertised name matches [name] (exact
/// preferred, else substring), subscribe to the BLE-MIDI characteristic, and
/// forward its notifications to the session event stream. Awaitable: returns
/// only once subscribed, so a subsequent `send_bytes` is safe.
Future<void> connect({required String name, required BigInt scanMs}) =>
    RustLib.instance.api.crateApiBleConnect(name: name, scanMs: scanMs);

/// Write raw bytes to the BLE-MIDI characteristic (write-without-response).
Future<void> sendBytes({required List<int> bytes}) =>
    RustLib.instance.api.crateApiBleSendBytes(bytes: bytes);

/// Disconnect the current device (and stop its forwarder). The session event
/// stream stays open.
Future<void> disconnect() => RustLib.instance.api.crateApiBleDisconnect();

/// A BLE device seen while scanning.
class BleDevice {
  final String name;
  final String address;
  final int rssi;

  const BleDevice({
    required this.name,
    required this.address,
    required this.rssi,
  });

  @override
  int get hashCode => name.hashCode ^ address.hashCode ^ rssi.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BleDevice &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          address == other.address &&
          rssi == other.rssi;
}
