// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import '../frb_generated.dart';

// These functions are ignored because they are not marked as `pub`: `blackman`, `conv1d_apply`, `conv1d`, `conv1x1`, `matmul`, `parse_wavenet`, `resample`, `run_wavenet`, `sinc`, `take`, `welch_wiener`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Cursor`, `LayerArray`, `LayerCfg`, `Layer`, `NamConfig`, `Nam`

/// Generates the clone-model arrays from a `.nam` (JSON) and the fixed reference
/// DI (mono, 44.1 kHz). Returns arrays at the device rate, ready for the `.clo`.
Future<CloArrays> generateCloArrays({
  required String namJson,
  required List<double> referenceDi44100,
}) => RustLib.instance.api.crateApiGeneratorGenerateCloArrays(
  namJson: namJson,
  referenceDi44100: referenceDi44100,
);

/// The clone model's FIR arrays + nonlinearity gains, ready for the `.clo`.
class CloArrays {
  final Float32List arrayA;
  final Float32List arrayB;
  final Float32List gains;

  const CloArrays({
    required this.arrayA,
    required this.arrayB,
    required this.gains,
  });

  @override
  int get hashCode => arrayA.hashCode ^ arrayB.hashCode ^ gains.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CloArrays &&
          runtimeType == other.runtimeType &&
          arrayA == other.arrayA &&
          arrayB == other.arrayB &&
          gains == other.gains;
}
