// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `connection_slot`, `events_slot`, `lock`, `port_matches`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Connection`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `clone`, `eq`, `fmt`, `fmt`

/// Enumerate all input and output MIDI ports currently visible to the host.
Future<List<MidiPort>> listPorts() =>
    RustLib.instance.api.crateApiMidiListPorts();

/// The session's inbound MIDI event stream: every received message, across all
/// connect/reconnect cycles, arrives here. On the Dart side this is a
/// `Stream<Uint8List>`. Call ONCE at startup and keep the subscription for the
/// app's lifetime; calling again replaces (and closes) the previous stream.
Stream<Uint8List> midiEvents() => RustLib.instance.api.crateApiMidiMidiEvents();

/// Opens the input+output ports whose names contain the given strings and
/// forwards received messages to the session event stream. Awaitable: it
/// completes only once both ports are open, so a subsequent `send_bytes` is
/// safe. State is mutated only after both ports open, so a failed open (e.g.
/// port not found) leaves any existing connection untouched.
Future<void> openConnection({
  required String inputName,
  required String outputName,
}) => RustLib.instance.api.crateApiMidiOpenConnection(
  inputName: inputName,
  outputName: outputName,
);

/// Sends raw bytes to the open output connection.
Future<void> sendBytes({required List<int> bytes}) =>
    RustLib.instance.api.crateApiMidiSendBytes(bytes: bytes);

/// Closes the current device connection (drops input+output). The session event
/// stream from `midi_events` stays open — "connected" is separate state.
Future<void> closeConnection() =>
    RustLib.instance.api.crateApiMidiCloseConnection();

/// Direction of a MIDI port.
enum MidiDirection { input, output }

/// A MIDI port the host exposes, identified by its (platform) name.
class MidiPort {
  final String name;
  final MidiDirection direction;

  const MidiPort({required this.name, required this.direction});

  @override
  int get hashCode => name.hashCode ^ direction.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MidiPort &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          direction == other.direction;
}
